# Automatically generated by configure - do not modify
SRC_PATH=/home/meisam/Desktop/faros-git-viber-taint2/faros/panda/qemu/roms/seabios
CC=gcc
CXX=g++
LINKER=g++
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
