/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-i386"
#define TARGET_SHORT_ALIGNMENT 2
#define TARGET_INT_ALIGNMENT 4
#define TARGET_LONG_ALIGNMENT 4
#define TARGET_LLONG_ALIGNMENT 8
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define CONFIG_NO_XEN 1
#define CONFIG_KVM 1
#define CONFIG_VHOST_NET 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
