/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "panda/pandalog.pb-c.h"
void   panda__taint_query_unique_label_set__init
                     (Panda__TaintQueryUniqueLabelSet         *message)
{
  static Panda__TaintQueryUniqueLabelSet init_value = PANDA__TAINT_QUERY_UNIQUE_LABEL_SET__INIT;
  *message = init_value;
}
size_t panda__taint_query_unique_label_set__get_packed_size
                     (const Panda__TaintQueryUniqueLabelSet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_unique_label_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__taint_query_unique_label_set__pack
                     (const Panda__TaintQueryUniqueLabelSet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_unique_label_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__taint_query_unique_label_set__pack_to_buffer
                     (const Panda__TaintQueryUniqueLabelSet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_unique_label_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintQueryUniqueLabelSet *
       panda__taint_query_unique_label_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintQueryUniqueLabelSet *)
     protobuf_c_message_unpack (&panda__taint_query_unique_label_set__descriptor,
                                allocator, len, data);
}
void   panda__taint_query_unique_label_set__free_unpacked
                     (Panda__TaintQueryUniqueLabelSet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_unique_label_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__src_info__init
                     (Panda__SrcInfo         *message)
{
  static Panda__SrcInfo init_value = PANDA__SRC_INFO__INIT;
  *message = init_value;
}
size_t panda__src_info__get_packed_size
                     (const Panda__SrcInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__src_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__src_info__pack
                     (const Panda__SrcInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__src_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__src_info__pack_to_buffer
                     (const Panda__SrcInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__src_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__SrcInfo *
       panda__src_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__SrcInfo *)
     protobuf_c_message_unpack (&panda__src_info__descriptor,
                                allocator, len, data);
}
void   panda__src_info__free_unpacked
                     (Panda__SrcInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__src_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__taint_query__init
                     (Panda__TaintQuery         *message)
{
  static Panda__TaintQuery init_value = PANDA__TAINT_QUERY__INIT;
  *message = init_value;
}
size_t panda__taint_query__get_packed_size
                     (const Panda__TaintQuery *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__taint_query__pack
                     (const Panda__TaintQuery *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__taint_query__pack_to_buffer
                     (const Panda__TaintQuery *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintQuery *
       panda__taint_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintQuery *)
     protobuf_c_message_unpack (&panda__taint_query__descriptor,
                                allocator, len, data);
}
void   panda__taint_query__free_unpacked
                     (Panda__TaintQuery *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__attack_point__init
                     (Panda__AttackPoint         *message)
{
  static Panda__AttackPoint init_value = PANDA__ATTACK_POINT__INIT;
  *message = init_value;
}
size_t panda__attack_point__get_packed_size
                     (const Panda__AttackPoint *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__attack_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__attack_point__pack
                     (const Panda__AttackPoint *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__attack_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__attack_point__pack_to_buffer
                     (const Panda__AttackPoint *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__attack_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__AttackPoint *
       panda__attack_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__AttackPoint *)
     protobuf_c_message_unpack (&panda__attack_point__descriptor,
                                allocator, len, data);
}
void   panda__attack_point__free_unpacked
                     (Panda__AttackPoint *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__attack_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__taint_query_hypercall__init
                     (Panda__TaintQueryHypercall         *message)
{
  static Panda__TaintQueryHypercall init_value = PANDA__TAINT_QUERY_HYPERCALL__INIT;
  *message = init_value;
}
size_t panda__taint_query_hypercall__get_packed_size
                     (const Panda__TaintQueryHypercall *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_hypercall__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__taint_query_hypercall__pack
                     (const Panda__TaintQueryHypercall *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_hypercall__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__taint_query_hypercall__pack_to_buffer
                     (const Panda__TaintQueryHypercall *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_hypercall__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintQueryHypercall *
       panda__taint_query_hypercall__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintQueryHypercall *)
     protobuf_c_message_unpack (&panda__taint_query_hypercall__descriptor,
                                allocator, len, data);
}
void   panda__taint_query_hypercall__free_unpacked
                     (Panda__TaintQueryHypercall *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__taint_query_hypercall__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__call_stack__init
                     (Panda__CallStack         *message)
{
  static Panda__CallStack init_value = PANDA__CALL_STACK__INIT;
  *message = init_value;
}
size_t panda__call_stack__get_packed_size
                     (const Panda__CallStack *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__call_stack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__call_stack__pack
                     (const Panda__CallStack *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__call_stack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__call_stack__pack_to_buffer
                     (const Panda__CallStack *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__call_stack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__CallStack *
       panda__call_stack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__CallStack *)
     protobuf_c_message_unpack (&panda__call_stack__descriptor,
                                allocator, len, data);
}
void   panda__call_stack__free_unpacked
                     (Panda__CallStack *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__call_stack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__bir__init
                     (Panda__Bir         *message)
{
  static Panda__Bir init_value = PANDA__BIR__INIT;
  *message = init_value;
}
size_t panda__bir__get_packed_size
                     (const Panda__Bir *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__bir__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__bir__pack
                     (const Panda__Bir *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__bir__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__bir__pack_to_buffer
                     (const Panda__Bir *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__bir__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__Bir *
       panda__bir__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__Bir *)
     protobuf_c_message_unpack (&panda__bir__descriptor,
                                allocator, len, data);
}
void   panda__bir__free_unpacked
                     (Panda__Bir *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__bir__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__tainted_branch__init
                     (Panda__TaintedBranch         *message)
{
  static Panda__TaintedBranch init_value = PANDA__TAINTED_BRANCH__INIT;
  *message = init_value;
}
size_t panda__tainted_branch__get_packed_size
                     (const Panda__TaintedBranch *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_branch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__tainted_branch__pack
                     (const Panda__TaintedBranch *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_branch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__tainted_branch__pack_to_buffer
                     (const Panda__TaintedBranch *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_branch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintedBranch *
       panda__tainted_branch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintedBranch *)
     protobuf_c_message_unpack (&panda__tainted_branch__descriptor,
                                allocator, len, data);
}
void   panda__tainted_branch__free_unpacked
                     (Panda__TaintedBranch *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_branch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__process__init
                     (Panda__Process         *message)
{
  static Panda__Process init_value = PANDA__PROCESS__INIT;
  *message = init_value;
}
size_t panda__process__get_packed_size
                     (const Panda__Process *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__process__pack
                     (const Panda__Process *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__process__pack_to_buffer
                     (const Panda__Process *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__Process *
       panda__process__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__Process *)
     protobuf_c_message_unpack (&panda__process__descriptor,
                                allocator, len, data);
}
void   panda__process__free_unpacked
                     (Panda__Process *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__nt_create_user_process__init
                     (Panda__NtCreateUserProcess         *message)
{
  static Panda__NtCreateUserProcess init_value = PANDA__NT_CREATE_USER_PROCESS__INIT;
  *message = init_value;
}
size_t panda__nt_create_user_process__get_packed_size
                     (const Panda__NtCreateUserProcess *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_create_user_process__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__nt_create_user_process__pack
                     (const Panda__NtCreateUserProcess *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_create_user_process__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__nt_create_user_process__pack_to_buffer
                     (const Panda__NtCreateUserProcess *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_create_user_process__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__NtCreateUserProcess *
       panda__nt_create_user_process__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__NtCreateUserProcess *)
     protobuf_c_message_unpack (&panda__nt_create_user_process__descriptor,
                                allocator, len, data);
}
void   panda__nt_create_user_process__free_unpacked
                     (Panda__NtCreateUserProcess *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_create_user_process__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__nt_terminate_process__init
                     (Panda__NtTerminateProcess         *message)
{
  static Panda__NtTerminateProcess init_value = PANDA__NT_TERMINATE_PROCESS__INIT;
  *message = init_value;
}
size_t panda__nt_terminate_process__get_packed_size
                     (const Panda__NtTerminateProcess *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_terminate_process__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__nt_terminate_process__pack
                     (const Panda__NtTerminateProcess *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_terminate_process__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__nt_terminate_process__pack_to_buffer
                     (const Panda__NtTerminateProcess *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_terminate_process__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__NtTerminateProcess *
       panda__nt_terminate_process__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__NtTerminateProcess *)
     protobuf_c_message_unpack (&panda__nt_terminate_process__descriptor,
                                allocator, len, data);
}
void   panda__nt_terminate_process__free_unpacked
                     (Panda__NtTerminateProcess *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__nt_terminate_process__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__process_file__init
                     (Panda__ProcessFile         *message)
{
  static Panda__ProcessFile init_value = PANDA__PROCESS_FILE__INIT;
  *message = init_value;
}
size_t panda__process_file__get_packed_size
                     (const Panda__ProcessFile *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__process_file__pack
                     (const Panda__ProcessFile *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__process_file__pack_to_buffer
                     (const Panda__ProcessFile *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__ProcessFile *
       panda__process_file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__ProcessFile *)
     protobuf_c_message_unpack (&panda__process_file__descriptor,
                                allocator, len, data);
}
void   panda__process_file__free_unpacked
                     (Panda__ProcessFile *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__process_key__init
                     (Panda__ProcessKey         *message)
{
  static Panda__ProcessKey init_value = PANDA__PROCESS_KEY__INIT;
  *message = init_value;
}
size_t panda__process_key__get_packed_size
                     (const Panda__ProcessKey *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__process_key__pack
                     (const Panda__ProcessKey *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__process_key__pack_to_buffer
                     (const Panda__ProcessKey *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__ProcessKey *
       panda__process_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__ProcessKey *)
     protobuf_c_message_unpack (&panda__process_key__descriptor,
                                allocator, len, data);
}
void   panda__process_key__free_unpacked
                     (Panda__ProcessKey *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__process_key_value__init
                     (Panda__ProcessKeyValue         *message)
{
  static Panda__ProcessKeyValue init_value = PANDA__PROCESS_KEY_VALUE__INIT;
  *message = init_value;
}
size_t panda__process_key_value__get_packed_size
                     (const Panda__ProcessKeyValue *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__process_key_value__pack
                     (const Panda__ProcessKeyValue *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__process_key_value__pack_to_buffer
                     (const Panda__ProcessKeyValue *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__ProcessKeyValue *
       panda__process_key_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__ProcessKeyValue *)
     protobuf_c_message_unpack (&panda__process_key_value__descriptor,
                                allocator, len, data);
}
void   panda__process_key_value__free_unpacked
                     (Panda__ProcessKeyValue *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__process_key_index__init
                     (Panda__ProcessKeyIndex         *message)
{
  static Panda__ProcessKeyIndex init_value = PANDA__PROCESS_KEY_INDEX__INIT;
  *message = init_value;
}
size_t panda__process_key_index__get_packed_size
                     (const Panda__ProcessKeyIndex *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__process_key_index__pack
                     (const Panda__ProcessKeyIndex *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__process_key_index__pack_to_buffer
                     (const Panda__ProcessKeyIndex *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__ProcessKeyIndex *
       panda__process_key_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__ProcessKeyIndex *)
     protobuf_c_message_unpack (&panda__process_key_index__descriptor,
                                allocator, len, data);
}
void   panda__process_key_index__free_unpacked
                     (Panda__ProcessKeyIndex *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__process_key_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__section__init
                     (Panda__Section         *message)
{
  static Panda__Section init_value = PANDA__SECTION__INIT;
  *message = init_value;
}
size_t panda__section__get_packed_size
                     (const Panda__Section *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__section__pack
                     (const Panda__Section *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__section__pack_to_buffer
                     (const Panda__Section *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__Section *
       panda__section__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__Section *)
     protobuf_c_message_unpack (&panda__section__descriptor,
                                allocator, len, data);
}
void   panda__section__free_unpacked
                     (Panda__Section *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__section_map_view__init
                     (Panda__SectionMapView         *message)
{
  static Panda__SectionMapView init_value = PANDA__SECTION_MAP_VIEW__INIT;
  *message = init_value;
}
size_t panda__section_map_view__get_packed_size
                     (const Panda__SectionMapView *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section_map_view__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__section_map_view__pack
                     (const Panda__SectionMapView *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section_map_view__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__section_map_view__pack_to_buffer
                     (const Panda__SectionMapView *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section_map_view__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__SectionMapView *
       panda__section_map_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__SectionMapView *)
     protobuf_c_message_unpack (&panda__section_map_view__descriptor,
                                allocator, len, data);
}
void   panda__section_map_view__free_unpacked
                     (Panda__SectionMapView *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__section_map_view__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__local_port__init
                     (Panda__LocalPort         *message)
{
  static Panda__LocalPort init_value = PANDA__LOCAL_PORT__INIT;
  *message = init_value;
}
size_t panda__local_port__get_packed_size
                     (const Panda__LocalPort *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__local_port__pack
                     (const Panda__LocalPort *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__local_port__pack_to_buffer
                     (const Panda__LocalPort *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__LocalPort *
       panda__local_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__LocalPort *)
     protobuf_c_message_unpack (&panda__local_port__descriptor,
                                allocator, len, data);
}
void   panda__local_port__free_unpacked
                     (Panda__LocalPort *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__local_port_init__init
                     (Panda__LocalPortInit         *message)
{
  static Panda__LocalPortInit init_value = PANDA__LOCAL_PORT_INIT__INIT;
  *message = init_value;
}
size_t panda__local_port_init__get_packed_size
                     (const Panda__LocalPortInit *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port_init__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__local_port_init__pack
                     (const Panda__LocalPortInit *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port_init__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__local_port_init__pack_to_buffer
                     (const Panda__LocalPortInit *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port_init__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__LocalPortInit *
       panda__local_port_init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__LocalPortInit *)
     protobuf_c_message_unpack (&panda__local_port_init__descriptor,
                                allocator, len, data);
}
void   panda__local_port_init__free_unpacked
                     (Panda__LocalPortInit *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__local_port_init__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__virtual_memory__init
                     (Panda__VirtualMemory         *message)
{
  static Panda__VirtualMemory init_value = PANDA__VIRTUAL_MEMORY__INIT;
  *message = init_value;
}
size_t panda__virtual_memory__get_packed_size
                     (const Panda__VirtualMemory *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__virtual_memory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__virtual_memory__pack
                     (const Panda__VirtualMemory *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__virtual_memory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__virtual_memory__pack_to_buffer
                     (const Panda__VirtualMemory *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__virtual_memory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__VirtualMemory *
       panda__virtual_memory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__VirtualMemory *)
     protobuf_c_message_unpack (&panda__virtual_memory__descriptor,
                                allocator, len, data);
}
void   panda__virtual_memory__free_unpacked
                     (Panda__VirtualMemory *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__virtual_memory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__tainted_instr__init
                     (Panda__TaintedInstr         *message)
{
  static Panda__TaintedInstr init_value = PANDA__TAINTED_INSTR__INIT;
  *message = init_value;
}
size_t panda__tainted_instr__get_packed_size
                     (const Panda__TaintedInstr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__tainted_instr__pack
                     (const Panda__TaintedInstr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__tainted_instr__pack_to_buffer
                     (const Panda__TaintedInstr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintedInstr *
       panda__tainted_instr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintedInstr *)
     protobuf_c_message_unpack (&panda__tainted_instr__descriptor,
                                allocator, len, data);
}
void   panda__tainted_instr__free_unpacked
                     (Panda__TaintedInstr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__tainted_instr_summary__init
                     (Panda__TaintedInstrSummary         *message)
{
  static Panda__TaintedInstrSummary init_value = PANDA__TAINTED_INSTR_SUMMARY__INIT;
  *message = init_value;
}
size_t panda__tainted_instr_summary__get_packed_size
                     (const Panda__TaintedInstrSummary *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr_summary__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__tainted_instr_summary__pack
                     (const Panda__TaintedInstrSummary *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr_summary__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__tainted_instr_summary__pack_to_buffer
                     (const Panda__TaintedInstrSummary *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr_summary__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__TaintedInstrSummary *
       panda__tainted_instr_summary__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__TaintedInstrSummary *)
     protobuf_c_message_unpack (&panda__tainted_instr_summary__descriptor,
                                allocator, len, data);
}
void   panda__tainted_instr_summary__free_unpacked
                     (Panda__TaintedInstrSummary *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__tainted_instr_summary__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   panda__log_entry__init
                     (Panda__LogEntry         *message)
{
  static Panda__LogEntry init_value = PANDA__LOG_ENTRY__INIT;
  *message = init_value;
}
size_t panda__log_entry__get_packed_size
                     (const Panda__LogEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__log_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t panda__log_entry__pack
                     (const Panda__LogEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__log_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t panda__log_entry__pack_to_buffer
                     (const Panda__LogEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__log_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Panda__LogEntry *
       panda__log_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Panda__LogEntry *)
     protobuf_c_message_unpack (&panda__log_entry__descriptor,
                                allocator, len, data);
}
void   panda__log_entry__free_unpacked
                     (Panda__LogEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &panda__log_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor panda__taint_query_unique_label_set__field_descriptors[2] =
{
  {
    "ptr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryUniqueLabelSet, ptr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryUniqueLabelSet, n_label),
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryUniqueLabelSet, label),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__taint_query_unique_label_set__field_indices_by_name[] = {
  1,   /* field[1] = label */
  0,   /* field[0] = ptr */
};
static const ProtobufCIntRange panda__taint_query_unique_label_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__taint_query_unique_label_set__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintQueryUniqueLabelSet",
  "TaintQueryUniqueLabelSet",
  "Panda__TaintQueryUniqueLabelSet",
  "panda",
  sizeof(Panda__TaintQueryUniqueLabelSet),
  2,
  panda__taint_query_unique_label_set__field_descriptors,
  panda__taint_query_unique_label_set__field_indices_by_name,
  1,  panda__taint_query_unique_label_set__number_ranges,
  (ProtobufCMessageInit) panda__taint_query_unique_label_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__src_info__field_descriptors[4] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__SrcInfo, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linenum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__SrcInfo, linenum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "astnodename",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__SrcInfo, astnodename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insertionpoint",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Panda__SrcInfo, has_insertionpoint),
    PROTOBUF_C_OFFSETOF(Panda__SrcInfo, insertionpoint),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__src_info__field_indices_by_name[] = {
  2,   /* field[2] = astnodename */
  0,   /* field[0] = filename */
  3,   /* field[3] = insertionpoint */
  1,   /* field[1] = linenum */
};
static const ProtobufCIntRange panda__src_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor panda__src_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.SrcInfo",
  "SrcInfo",
  "Panda__SrcInfo",
  "panda",
  sizeof(Panda__SrcInfo),
  4,
  panda__src_info__field_descriptors,
  panda__src_info__field_indices_by_name,
  1,  panda__src_info__number_ranges,
  (ProtobufCMessageInit) panda__src_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__taint_query__field_descriptors[4] =
{
  {
    "ptr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQuery, ptr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQuery, tcn),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQuery, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unique_label_set",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQuery, unique_label_set),
    &panda__taint_query_unique_label_set__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__taint_query__field_indices_by_name[] = {
  2,   /* field[2] = offset */
  0,   /* field[0] = ptr */
  1,   /* field[1] = tcn */
  3,   /* field[3] = unique_label_set */
};
static const ProtobufCIntRange panda__taint_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor panda__taint_query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintQuery",
  "TaintQuery",
  "Panda__TaintQuery",
  "panda",
  sizeof(Panda__TaintQuery),
  4,
  panda__taint_query__field_descriptors,
  panda__taint_query__field_indices_by_name,
  1,  panda__taint_query__number_ranges,
  (ProtobufCMessageInit) panda__taint_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__attack_point__field_descriptors[3] =
{
  {
    "info",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__AttackPoint, info),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_stack",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__AttackPoint, call_stack),
    &panda__call_stack__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_info",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__AttackPoint, src_info),
    &panda__src_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__attack_point__field_indices_by_name[] = {
  1,   /* field[1] = call_stack */
  0,   /* field[0] = info */
  2,   /* field[2] = src_info */
};
static const ProtobufCIntRange panda__attack_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor panda__attack_point__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.AttackPoint",
  "AttackPoint",
  "Panda__AttackPoint",
  "panda",
  sizeof(Panda__AttackPoint),
  3,
  panda__attack_point__field_descriptors,
  panda__attack_point__field_indices_by_name,
  1,  panda__attack_point__number_ranges,
  (ProtobufCMessageInit) panda__attack_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__taint_query_hypercall__field_descriptors[7] =
{
  {
    "buf",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, buf),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, len),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, n_data),
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_tainted",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, num_tainted),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_stack",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, call_stack),
    &panda__call_stack__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_info",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, src_info),
    &panda__src_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_query",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, n_taint_query),
    PROTOBUF_C_OFFSETOF(Panda__TaintQueryHypercall, taint_query),
    &panda__taint_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__taint_query_hypercall__field_indices_by_name[] = {
  0,   /* field[0] = buf */
  4,   /* field[4] = call_stack */
  2,   /* field[2] = data */
  1,   /* field[1] = len */
  3,   /* field[3] = num_tainted */
  5,   /* field[5] = src_info */
  6,   /* field[6] = taint_query */
};
static const ProtobufCIntRange panda__taint_query_hypercall__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor panda__taint_query_hypercall__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintQueryHypercall",
  "TaintQueryHypercall",
  "Panda__TaintQueryHypercall",
  "panda",
  sizeof(Panda__TaintQueryHypercall),
  7,
  panda__taint_query_hypercall__field_descriptors,
  panda__taint_query_hypercall__field_indices_by_name,
  1,  panda__taint_query_hypercall__number_ranges,
  (ProtobufCMessageInit) panda__taint_query_hypercall__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__call_stack__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Panda__CallStack, n_addr),
    PROTOBUF_C_OFFSETOF(Panda__CallStack, addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__call_stack__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange panda__call_stack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor panda__call_stack__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.CallStack",
  "CallStack",
  "Panda__CallStack",
  "panda",
  sizeof(Panda__CallStack),
  1,
  panda__call_stack__field_descriptors,
  panda__call_stack__field_indices_by_name,
  1,  panda__call_stack__number_ranges,
  (ProtobufCMessageInit) panda__call_stack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__bir__field_descriptors[5] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Bir, len),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cached",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Bir, cached),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "highscore",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Bir, highscore),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Bir, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Panda__Bir, has_offset),
    PROTOBUF_C_OFFSETOF(Panda__Bir, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__bir__field_indices_by_name[] = {
  1,   /* field[1] = cached */
  3,   /* field[3] = filename */
  2,   /* field[2] = highscore */
  0,   /* field[0] = len */
  4,   /* field[4] = offset */
};
static const ProtobufCIntRange panda__bir__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor panda__bir__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.Bir",
  "Bir",
  "Panda__Bir",
  "panda",
  sizeof(Panda__Bir),
  5,
  panda__bir__field_descriptors,
  panda__bir__field_indices_by_name,
  1,  panda__bir__number_ranges,
  (ProtobufCMessageInit) panda__bir__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__tainted_branch__field_descriptors[2] =
{
  {
    "call_stack",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintedBranch, call_stack),
    &panda__call_stack__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_query",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Panda__TaintedBranch, n_taint_query),
    PROTOBUF_C_OFFSETOF(Panda__TaintedBranch, taint_query),
    &panda__taint_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__tainted_branch__field_indices_by_name[] = {
  0,   /* field[0] = call_stack */
  1,   /* field[1] = taint_query */
};
static const ProtobufCIntRange panda__tainted_branch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__tainted_branch__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintedBranch",
  "TaintedBranch",
  "Panda__TaintedBranch",
  "panda",
  sizeof(Panda__TaintedBranch),
  2,
  panda__tainted_branch__field_descriptors,
  panda__tainted_branch__field_indices_by_name,
  1,  panda__tainted_branch__number_ranges,
  (ProtobufCMessageInit) panda__tainted_branch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__process__field_descriptors[2] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Process, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Process, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__process__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange panda__process__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__process__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.Process",
  "Process",
  "Panda__Process",
  "panda",
  sizeof(Panda__Process),
  2,
  panda__process__field_descriptors,
  panda__process__field_indices_by_name,
  1,  panda__process__number_ranges,
  (ProtobufCMessageInit) panda__process__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__nt_create_user_process__field_descriptors[3] =
{
  {
    "cur_p",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__NtCreateUserProcess, cur_p),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_p",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__NtCreateUserProcess, new_p),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_long_name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__NtCreateUserProcess, new_long_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__nt_create_user_process__field_indices_by_name[] = {
  0,   /* field[0] = cur_p */
  2,   /* field[2] = new_long_name */
  1,   /* field[1] = new_p */
};
static const ProtobufCIntRange panda__nt_create_user_process__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor panda__nt_create_user_process__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.NtCreateUserProcess",
  "NtCreateUserProcess",
  "Panda__NtCreateUserProcess",
  "panda",
  sizeof(Panda__NtCreateUserProcess),
  3,
  panda__nt_create_user_process__field_descriptors,
  panda__nt_create_user_process__field_indices_by_name,
  1,  panda__nt_create_user_process__number_ranges,
  (ProtobufCMessageInit) panda__nt_create_user_process__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__nt_terminate_process__field_descriptors[2] =
{
  {
    "cur_p",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__NtTerminateProcess, cur_p),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "term_p",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__NtTerminateProcess, term_p),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__nt_terminate_process__field_indices_by_name[] = {
  0,   /* field[0] = cur_p */
  1,   /* field[1] = term_p */
};
static const ProtobufCIntRange panda__nt_terminate_process__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__nt_terminate_process__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.NtTerminateProcess",
  "NtTerminateProcess",
  "Panda__NtTerminateProcess",
  "panda",
  sizeof(Panda__NtTerminateProcess),
  2,
  panda__nt_terminate_process__field_descriptors,
  panda__nt_terminate_process__field_indices_by_name,
  1,  panda__nt_terminate_process__number_ranges,
  (ProtobufCMessageInit) panda__nt_terminate_process__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__process_file__field_descriptors[2] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessFile, proc),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessFile, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__process_file__field_indices_by_name[] = {
  1,   /* field[1] = filename */
  0,   /* field[0] = proc */
};
static const ProtobufCIntRange panda__process_file__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__process_file__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.ProcessFile",
  "ProcessFile",
  "Panda__ProcessFile",
  "panda",
  sizeof(Panda__ProcessFile),
  2,
  panda__process_file__field_descriptors,
  panda__process_file__field_indices_by_name,
  1,  panda__process_file__number_ranges,
  (ProtobufCMessageInit) panda__process_file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__process_key__field_descriptors[2] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKey, proc),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKey, keyname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__process_key__field_indices_by_name[] = {
  1,   /* field[1] = keyname */
  0,   /* field[0] = proc */
};
static const ProtobufCIntRange panda__process_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__process_key__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.ProcessKey",
  "ProcessKey",
  "Panda__ProcessKey",
  "panda",
  sizeof(Panda__ProcessKey),
  2,
  panda__process_key__field_descriptors,
  panda__process_key__field_indices_by_name,
  1,  panda__process_key__number_ranges,
  (ProtobufCMessageInit) panda__process_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__process_key_value__field_descriptors[2] =
{
  {
    "pk",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKeyValue, pk),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKeyValue, value_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__process_key_value__field_indices_by_name[] = {
  0,   /* field[0] = pk */
  1,   /* field[1] = value_name */
};
static const ProtobufCIntRange panda__process_key_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__process_key_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.ProcessKeyValue",
  "ProcessKeyValue",
  "Panda__ProcessKeyValue",
  "panda",
  sizeof(Panda__ProcessKeyValue),
  2,
  panda__process_key_value__field_descriptors,
  panda__process_key_value__field_indices_by_name,
  1,  panda__process_key_value__number_ranges,
  (ProtobufCMessageInit) panda__process_key_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__process_key_index__field_descriptors[2] =
{
  {
    "pk",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKeyIndex, pk),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__ProcessKeyIndex, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__process_key_index__field_indices_by_name[] = {
  1,   /* field[1] = index */
  0,   /* field[0] = pk */
};
static const ProtobufCIntRange panda__process_key_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__process_key_index__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.ProcessKeyIndex",
  "ProcessKeyIndex",
  "Panda__ProcessKeyIndex",
  "panda",
  sizeof(Panda__ProcessKeyIndex),
  2,
  panda__process_key_index__field_descriptors,
  panda__process_key_index__field_indices_by_name,
  1,  panda__process_key_index__number_ranges,
  (ProtobufCMessageInit) panda__process_key_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__section__field_descriptors[4] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Section, proc),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Section, section_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Section, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__Section, file_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__section__field_indices_by_name[] = {
  3,   /* field[3] = file_name */
  2,   /* field[2] = name */
  0,   /* field[0] = proc */
  1,   /* field[1] = section_id */
};
static const ProtobufCIntRange panda__section__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor panda__section__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.Section",
  "Section",
  "Panda__Section",
  "panda",
  sizeof(Panda__Section),
  4,
  panda__section__field_descriptors,
  panda__section__field_indices_by_name,
  1,  panda__section__number_ranges,
  (ProtobufCMessageInit) panda__section__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__section_map_view__field_descriptors[2] =
{
  {
    "section",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__SectionMapView, section),
    &panda__section__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__SectionMapView, target),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__section_map_view__field_indices_by_name[] = {
  0,   /* field[0] = section */
  1,   /* field[1] = target */
};
static const ProtobufCIntRange panda__section_map_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__section_map_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.SectionMapView",
  "SectionMapView",
  "Panda__SectionMapView",
  "panda",
  sizeof(Panda__SectionMapView),
  2,
  panda__section_map_view__field_descriptors,
  panda__section_map_view__field_indices_by_name,
  1,  panda__section_map_view__number_ranges,
  (ProtobufCMessageInit) panda__section_map_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__local_port__field_descriptors[4] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPort, proc),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPort, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPort, client),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPort, server),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__local_port__field_indices_by_name[] = {
  2,   /* field[2] = client */
  1,   /* field[1] = id */
  0,   /* field[0] = proc */
  3,   /* field[3] = server */
};
static const ProtobufCIntRange panda__local_port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor panda__local_port__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.LocalPort",
  "LocalPort",
  "Panda__LocalPort",
  "panda",
  sizeof(Panda__LocalPort),
  4,
  panda__local_port__field_descriptors,
  panda__local_port__field_indices_by_name,
  1,  panda__local_port__number_ranges,
  (ProtobufCMessageInit) panda__local_port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__local_port_init__field_descriptors[2] =
{
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPortInit, port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port_name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LocalPortInit, port_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__local_port_init__field_indices_by_name[] = {
  0,   /* field[0] = port */
  1,   /* field[1] = port_name */
};
static const ProtobufCIntRange panda__local_port_init__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__local_port_init__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.LocalPortInit",
  "LocalPortInit",
  "Panda__LocalPortInit",
  "panda",
  sizeof(Panda__LocalPortInit),
  2,
  panda__local_port_init__field_descriptors,
  panda__local_port_init__field_indices_by_name,
  1,  panda__local_port_init__number_ranges,
  (ProtobufCMessageInit) panda__local_port_init__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__virtual_memory__field_descriptors[2] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__VirtualMemory, proc),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__VirtualMemory, target),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__virtual_memory__field_indices_by_name[] = {
  0,   /* field[0] = proc */
  1,   /* field[1] = target */
};
static const ProtobufCIntRange panda__virtual_memory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__virtual_memory__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.VirtualMemory",
  "VirtualMemory",
  "Panda__VirtualMemory",
  "panda",
  sizeof(Panda__VirtualMemory),
  2,
  panda__virtual_memory__field_descriptors,
  panda__virtual_memory__field_indices_by_name,
  1,  panda__virtual_memory__number_ranges,
  (ProtobufCMessageInit) panda__virtual_memory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__tainted_instr__field_descriptors[2] =
{
  {
    "call_stack",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintedInstr, call_stack),
    &panda__call_stack__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_query",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Panda__TaintedInstr, n_taint_query),
    PROTOBUF_C_OFFSETOF(Panda__TaintedInstr, taint_query),
    &panda__taint_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__tainted_instr__field_indices_by_name[] = {
  0,   /* field[0] = call_stack */
  1,   /* field[1] = taint_query */
};
static const ProtobufCIntRange panda__tainted_instr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__tainted_instr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintedInstr",
  "TaintedInstr",
  "Panda__TaintedInstr",
  "panda",
  sizeof(Panda__TaintedInstr),
  2,
  panda__tainted_instr__field_descriptors,
  panda__tainted_instr__field_indices_by_name,
  1,  panda__tainted_instr__number_ranges,
  (ProtobufCMessageInit) panda__tainted_instr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__tainted_instr_summary__field_descriptors[2] =
{
  {
    "asid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintedInstrSummary, asid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__TaintedInstrSummary, pc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__tainted_instr_summary__field_indices_by_name[] = {
  0,   /* field[0] = asid */
  1,   /* field[1] = pc */
};
static const ProtobufCIntRange panda__tainted_instr_summary__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor panda__tainted_instr_summary__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.TaintedInstrSummary",
  "TaintedInstrSummary",
  "Panda__TaintedInstrSummary",
  "panda",
  sizeof(Panda__TaintedInstrSummary),
  2,
  panda__tainted_instr_summary__field_descriptors,
  panda__tainted_instr_summary__field_indices_by_name,
  1,  panda__tainted_instr_summary__number_ranges,
  (ProtobufCMessageInit) panda__tainted_instr_summary__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor panda__log_entry__field_descriptors[51] =
{
  {
    "pc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, pc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, instr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, has_asid),
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, asid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "process_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, process_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "process_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, has_process_id),
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, process_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_label_virtual_addr",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, has_taint_label_virtual_addr),
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, taint_label_virtual_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_label_physical_addr",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, has_taint_label_physical_addr),
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, taint_label_physical_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_label_number",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, has_taint_label_number),
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, taint_label_number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_stack",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, call_stack),
    &panda__call_stack__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_pid",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, new_pid),
    &panda__process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_user_process",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_user_process),
    &panda__nt_create_user_process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_terminate_process",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_terminate_process),
    &panda__nt_terminate_process__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_file",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_file),
    &panda__process_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_read_file",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_read_file),
    &panda__process_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_delete_file",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_delete_file),
    &panda__process_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_write_file",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_write_file),
    &panda__process_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_key",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_key),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_key_transacted",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_key_transacted),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_open_key",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_open_key),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_open_key_ex",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_open_key_ex),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_open_key_transacted",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_open_key_transacted),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_open_key_transacted_ex",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_open_key_transacted_ex),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_delete_key",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_delete_key),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_query_key",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_query_key),
    &panda__process_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_query_value_key",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_query_value_key),
    &panda__process_key_value__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_delete_value_key",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_delete_value_key),
    &panda__process_key_value__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_enumerate_key",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_enumerate_key),
    &panda__process_key_index__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_enumerate_value_key",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_enumerate_value_key),
    &panda__process_key_index__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_set_value_key",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_set_value_key),
    &panda__process_key_value__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tainted_branch",
    36,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, tainted_branch),
    &panda__tainted_branch__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tainted_instr",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, tainted_instr),
    &panda__tainted_instr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_query_hypercall",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, taint_query_hypercall),
    &panda__taint_query_hypercall__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attack_point",
    39,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, attack_point),
    &panda__attack_point__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_section",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_section),
    &panda__section__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_open_section",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_open_section),
    &panda__section__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_map_view_of_section",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_map_view_of_section),
    &panda__section_map_view__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_create_port",
    43,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_create_port),
    &panda__local_port_init__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_connect_port",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_connect_port),
    &panda__local_port_init__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_listen_port",
    45,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_listen_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_accept_connect_port",
    46,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_accept_connect_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_complete_connect_port",
    47,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_complete_connect_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_request_port",
    48,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_request_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_request_wait_reply_port",
    49,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_request_wait_reply_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_reply_port",
    50,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_reply_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_reply_wait_reply_port",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_reply_wait_reply_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_reply_wait_receive_port",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_reply_wait_receive_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_impersonate_client_of_port",
    53,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_impersonate_client_of_port),
    &panda__local_port__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_read_virtual_memory",
    54,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_read_virtual_memory),
    &panda__virtual_memory__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nt_write_virtual_memory",
    55,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, nt_write_virtual_memory),
    &panda__virtual_memory__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tainted_instr_summary",
    56,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, tainted_instr_summary),
    &panda__tainted_instr_summary__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bir",
    57,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Panda__LogEntry, bir),
    &panda__bir__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned panda__log_entry__field_indices_by_name[] = {
  2,   /* field[2] = asid */
  32,   /* field[32] = attack_point */
  50,   /* field[50] = bir */
  8,   /* field[8] = call_stack */
  1,   /* field[1] = instr */
  9,   /* field[9] = new_pid */
  39,   /* field[39] = nt_accept_connect_port */
  40,   /* field[40] = nt_complete_connect_port */
  37,   /* field[37] = nt_connect_port */
  12,   /* field[12] = nt_create_file */
  16,   /* field[16] = nt_create_key */
  17,   /* field[17] = nt_create_key_transacted */
  36,   /* field[36] = nt_create_port */
  33,   /* field[33] = nt_create_section */
  10,   /* field[10] = nt_create_user_process */
  14,   /* field[14] = nt_delete_file */
  22,   /* field[22] = nt_delete_key */
  25,   /* field[25] = nt_delete_value_key */
  26,   /* field[26] = nt_enumerate_key */
  27,   /* field[27] = nt_enumerate_value_key */
  46,   /* field[46] = nt_impersonate_client_of_port */
  38,   /* field[38] = nt_listen_port */
  35,   /* field[35] = nt_map_view_of_section */
  18,   /* field[18] = nt_open_key */
  19,   /* field[19] = nt_open_key_ex */
  20,   /* field[20] = nt_open_key_transacted */
  21,   /* field[21] = nt_open_key_transacted_ex */
  34,   /* field[34] = nt_open_section */
  23,   /* field[23] = nt_query_key */
  24,   /* field[24] = nt_query_value_key */
  13,   /* field[13] = nt_read_file */
  47,   /* field[47] = nt_read_virtual_memory */
  43,   /* field[43] = nt_reply_port */
  45,   /* field[45] = nt_reply_wait_receive_port */
  44,   /* field[44] = nt_reply_wait_reply_port */
  41,   /* field[41] = nt_request_port */
  42,   /* field[42] = nt_request_wait_reply_port */
  28,   /* field[28] = nt_set_value_key */
  11,   /* field[11] = nt_terminate_process */
  15,   /* field[15] = nt_write_file */
  48,   /* field[48] = nt_write_virtual_memory */
  0,   /* field[0] = pc */
  4,   /* field[4] = process_id */
  3,   /* field[3] = process_name */
  7,   /* field[7] = taint_label_number */
  6,   /* field[6] = taint_label_physical_addr */
  5,   /* field[5] = taint_label_virtual_addr */
  31,   /* field[31] = taint_query_hypercall */
  29,   /* field[29] = tainted_branch */
  30,   /* field[30] = tainted_instr */
  49,   /* field[49] = tainted_instr_summary */
};
static const ProtobufCIntRange panda__log_entry__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 10, 8 },
  { 27, 24 },
  { 36, 29 },
  { 0, 51 }
};
const ProtobufCMessageDescriptor panda__log_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "panda.LogEntry",
  "LogEntry",
  "Panda__LogEntry",
  "panda",
  sizeof(Panda__LogEntry),
  51,
  panda__log_entry__field_descriptors,
  panda__log_entry__field_indices_by_name,
  4,  panda__log_entry__number_ranges,
  (ProtobufCMessageInit) panda__log_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
